# 프라미스

[https://ko.javascript.info/promise-basics](https://ko.javascript.info/promise-basics)

프라미스는 콜백을 아래와 같은 프로세스로 바꾼다.

* 제작 코드는 원격에서 스크립트를 불러올 것 같은 시간이 걸리는 일을 한다. 
* 소비 코드는 제작 코드의 결과를 기다렸다 이를 소비한다. 
* 프라미스는 제작코드와 소비코드를 연결하는 자바스크립트 객체이다. 

프라미스는 아래와 같은 문법으로 만든다. 
```js
let promise = new Promise(function(resolve, reject) {
  // 제작 코드 executor
});
```

~~executor는 제작코드를 감싸는 함수인듯?~~

이때 new Promise에 전달되는 함수는 **실행 함수**라 부른다. new Promise가 만들어질 때 자동적으로 실행되고 결과를 최종적으로 만들어내는 제작코드를 포함한다. 

이때 executor의 인수인 resolve와 reject는 자바스크립트에서 자체 제공하는 콜백이다. 이거 상관없이 제작코드만 만들면 된다. 

**대신** executor에서 결과를 인수로 넘겨준 콜백 중 반드시 하나를 호출해야 한다. 

* resolve(value) -> 일이 성공적으로 끝난 경우 그 결과를 value와 함께 호출
* reject(error) -> 에러 발생 시 객체를 나타내는 error와 함께 호출

즉, executor는 자동적으로 실행되고 일을 처리한다. 처리가 끝나면 성공 여부에 따라 resolve와 reject를 호출한다. 

new Promise생성자가 반환하는 promise 객체는 다음과 같은 내부 프로퍼티를 갖는다. 

* state -> 처음엔 보류하다 resolve가 호출되면 "fulfilled", reject가 호출되면 "rejected"로 변한다. 
* result -> 처음엔 undefined. resolve가 호출되면 value로, reject가 호출되면 error로 변한다. 

## 프라미스의 성질 

* 프라미스는 성공 또는 실패만 한다. 
* Error객체와 함께 거부하기. reject를 만들 때는 Error 객체 또는 error를 상속받은 객체 사용을 권장한다. 
* resolve, reject함수 즉시 호출: 즉시 호출도 가능하다. 
* state와 result는 내부에 있다. 직접 접근이 안된다!

## 소비자: then, catch, finally

소비함수는 .then, .catch, .finally메서드를 이용한다. 

### then

**.then은 프라미스에서 가장 중요하다. **

```js
promise.then(
  function(result) { /* 결과(result)를 다룹니다 */ },
  function(error) { /* 에러(error)를 다룹니다 */ }
);
```

.then((result) => {...}, (error) => {...})의 첫 인수는 프라미스가 이행됐을 때, 다음 인수는 거부됐을 때 실행되는 함수를 나타낸다. 

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("완료!"), 1000);
});

// resolve 함수는 .then의 첫 번째 함수(인수)를 실행합니다.
promise.then(
  result => alert(result), // 1초 후 "완료!"를 출력
  error => alert(error) // 실행되지 않음
);
``` 

위의 예시에서는 error가 사용되지 않는다. 

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// reject 함수는 .then의 두 번째 함수를 실행합니다.
promise.then(
  result => alert(result), // 실행되지 않음
  error => alert(error) // 1초 후 "Error: 에러 발생!"을 출력
);
```

위의 경우 두 번째 함수가 실행된다. 

성공한 경우만 처리한다면, .then에 인수를 하나만 전달하면 된다. 

### catch

에러발생시만 다룬다면 catch를 쓰는 경우도 있다. 

```js
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// .catch(f)는 promise.then(null, f)과 동일하게 작동합니다
promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
```

### finally

그냥 무조건 실행할 경우, finally(f)를 사용한다. 이것은 then(f, f)와 동일하다라고 하다가 차이점이 있다고 한다. 

* finally 핸들러에는 인수가 없다. finally에선 프라미스가 이행됐는지 거부됐는지 알 수 없다. 
* finally 핸들러는 자동으로 다음 핸들러에 결과와 에러를 전달한다. (result와 error를 둘 다 전달)

ex) loadscript

```js
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`${src}를 불러오는 도중에 에러가 발생함`));

  document.head.append(script);
}

function loadScript(src) {
  return new Promise(function(resolve, reject) {
    let script = document.createElement('script');
    script.src = src;

    script.onload = () => resolve(script);
    script.onerror = () => reject(new Error(`${src}를 불러오는 도중에 에러가 발생함`));

    document.head.append(script);
  });
}
```

위의 코드를 프라미스를 이용하면

```js
let promise = loadScript("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js");

promise.then(
  script => alert(`${script.src}을 불러왔습니다!`),
  error => alert(`Error: ${error.message}`)
);

promise.then(script => alert('또다른 핸들러...'));
```

으로 바꿀 수 있다. 